global_costmap:
  global_frame: odom
  robot_base_frame: $(arg robot_namespace)/base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  rolling_window: true
  width: 50.0
  height: 50.0
  resolution: 0.05
  origin_x: -25.0
  origin_y: -25.0