joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  odom_frame_id: odom
  base_frame_id: "$(arg robot_namespace)/base_link"
  left_wheel: ['$(arg robot_namespace)/wheel_left_joint']
  right_wheel: ['$(arg robot_namespace)/wheel_right_joint']
  publish_rate: 50
  pose_covariance_diagonal: [
    0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [
    0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  k_l: 0.1
  k_r: 0.1

  # odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and diameter.
  #wheel_separation : 0.230
  #wheel_radius : 0.035

  # wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0

  # velocity and acceleration limits
  # whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2
