# set map config
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0

# base footprint of the robot (basically its convex hull on the ground)
footprint: [
  [0.254, -0.230],
  [-0.254, -0.230],
  [-0.254, 0.230],
  [0.254, 0.230]]

footprint_padding: 0.1

# map parameters
transform_tolerance: 0.5
meter_scoring: true

# cost parameters
cost_scaling_factor: 10.0
lethal_cost_threshold: 100

# plugins
plugins:
  - { name: obstacle_layer_laser, type: "costmap_2d::ObstacleLayer" }
  - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

obstacle_layer_laser:
  observation_sources: hokuyo_utm30lx
  hokuyo_utm30lx: {
    sensor_frame: top_laser_frame,
    data_type: LaserScan,
    topic: /laser/scan,
    marking: true,
    clearing: true,
    min_obstacle_height: -20.0,
    max_obstacle_height: 20.0,
    obstacle_range: 2.5, # range within which obstacles are registered
    raytrace_range: 3.0, # range upto which sensor clears the map
    inf_is_valid: true,
  }

inflation_layer:
  inflation_radius: 0.3