global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 5.0
  static_map: true
  rolling_window: false
  width: 50.0
  height: 50.0
  resolution: 0.025
  origin_x: -25.0
  origin_y: -25.0
  map_type: voxel
  lethal_cost_threshold: 100
  track_unknown_space: true
  unknown_cost_value: 255

# plugins
plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}