local_costmap:
  global_frame: map
  robot_base_frame: $(arg robot_namespace)/base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05

  inflation_layer:
    inflation_radius: 0.15